version: '3.8'
services:
  db:
    image: postgres:14.2
    stop_signal: SIGINT
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  konyha-next:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: konyha-next
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
volumes:
  db:
    driver: local
