version: '3.8'
services:
  db:
    image: postgres:14.2
    stop_signal: SIGINT
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  manager:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manager
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - MANAGER_DOMAIN="http://localhost:3000"
      - SITEGEN_DOMAIN="http://localhost:7777"
      - HOST="localhost"
    env_file:
      - .env
  sitegen:
    stdin_open: true
    build:
      context: ./sitegen
      dockerfile: ./Dockerfile
    container_name: sitegen
    ports:
      - "7777:7777"
    restart: unless-stopped
volumes:
  db:
    driver: local
