version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: "no"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  graphql-engine:
    image: hasura/graphql-engine:v2.5.1
    ports:
    - "8000:8080"
    depends_on:
    - "postgres"
    restart: "no"
    env_file:
      - .env
volumes:
  db_data:
