name: Docker Image CI

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Docker Build
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:latest
    
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:latest
